/**
 * MathMind Package Manager
 * Handles creating, loading, and compiling math content packages.
 */

const addContentBtn = document.getElementById("add-content-btn");
if (addContentBtn) addContentBtn.onclick = addContentRow;

function addContentRow(content = {}) {
  const tableBody = document.getElementById("content-table").querySelector("tbody");
  const rowContent = `
    <tr>
      <td contenteditable="true">${content.Name || ""}</td>
      <td contenteditable="true">${content.Description || ""}</td>
      <td contenteditable="true">${content.Content || ""}</td>
    </tr>
  `;
  tableBody.insertAdjacentHTML('beforeend', rowContent);
}

const removeContentBtn = document.getElementById("remove-content-btn");
if (removeContentBtn) removeContentBtn.onclick = removeLastContentRow;

function removeLastContentRow() {
  const tableBody = document.getElementById("content-table").querySelector("tbody");
  if (tableBody.rows.length > 0) {
    tableBody.deleteRow(-1);
  }
}

const loadPackageBtn = document.getElementById("load-package-btn");
if (loadPackageBtn) loadPackageBtn.onclick = loadPackage;

function loadPackage() {
  const fileInput = document.getElementById("package-file");
  const file = fileInput.files[0];

  if (!file) {
    alert("Please select a valid .json file.");
    return;
  }

  const reader = new FileReader();
  reader.onload = function (event) {
    try {
      const packageData = JSON.parse(event.target.result);
      const manifest = packageData.Manifest;
      const contents = packageData.Content;

      document.getElementById("package-name").value = manifest.PackageName;
      document.getElementById("package-id").value = manifest.PackageId;
      document.getElementById("version").value = manifest.Version;
      document.getElementById("author").value = manifest.Author;
      document.getElementById("description").value = manifest.Description;
      document.getElementById("keywords").value = manifest.Keywords.join(", ");
      document.getElementById("license").value = manifest.License;

      const tableBody = document.getElementById("content-table").querySelector("tbody");
      tableBody.innerHTML = "";

      contents.forEach(content => {
        addContentRow(content);
      });

    } catch (error) {
      alert("Error reading package file: " + error.message);
    }
  };
  reader.readAsText(file);
}

const savePackageBtn = document.getElementById("save-package-btn");
if (savePackageBtn) savePackageBtn.onclick = savePackage;

function savePackage() {
  const packageName = document.getElementById("package-name").value;
  const packageId = document.getElementById("package-id").value;
  const version = document.getElementById("version").value;
  const author = document.getElementById("author").value;
  const description = document.getElementById("description").value;
  const keywords = document.getElementById("keywords").value.split(",").map(k => k.trim());
  const license = document.getElementById("license").value;

  const contents = [];
  const rows = document.getElementById("content-table").querySelectorAll("tbody tr");
  rows.forEach(row => {
    const name = row.cells[0].innerText;
    const desc = row.cells[1].innerText;
    const content = row.cells[2].innerText;
    contents.push({ Name: name, Description: desc, Content: content });
  });

  const packageData = {
    Manifest: {
      PackageName: packageName,
      PackageId: packageId,
      Version: version,
      Author: author,
      Description: description,
      Keywords: keywords,
      License: license
    },
    Content: contents
  };

  const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(packageData, null, 2));
  const downloadAnchorNode = document.createElement('a');
  downloadAnchorNode.setAttribute("href", dataStr);
  downloadAnchorNode.setAttribute("download", `${packageId}_v${version}.json`);
  document.body.appendChild(downloadAnchorNode);
  downloadAnchorNode.click();
  downloadAnchorNode.remove();
}

const compileBtn = document.getElementById("compile-btn");
if (compileBtn) compileBtn.onclick = compileToLua;

function compileToLua() {
  const contents = [];
  const rows = document.getElementById("content-table").querySelectorAll("tbody tr");
  rows.forEach(row => {
    const name = row.cells[0].innerText;
    const desc = row.cells[1].innerText;
    const content = row.cells[2].innerText;
    contents.push({ Name: name, Description: desc, Content: content });
  });

  const luaLines = [
    "-- Generated by MathMind Package Manager",
    "local data = {"
  ];

  contents.forEach(item => {
    luaLines.push(`  ["${item.Name}"] = [[${item.Content}]],`);
  });

  luaLines.push("}");
  luaLines.push("return data");

  const luaContent = luaLines.join("\n");
  document.getElementById("lua-output").value = luaContent;
}

const copyLuaBtn = document.getElementById("copy-lua-btn");
if (copyLuaBtn) copyLuaBtn.onclick = copyToClipboard;

function copyToClipboard() {
  const luaOutput = document.getElementById("lua-output");
  luaOutput.select();
  document.execCommand("copy");
  alert("Lua code copied to clipboard!");
}

// Initialize with one empty row if needed
window.addEventListener('DOMContentLoaded', () => {
  const tableBody = document.getElementById("content-table").querySelector("tbody");
  if (tableBody && tableBody.rows.length === 0) {
    addContentRow();
  }
});
